function [Forces_body, Moments_body, mdot_total] = calculate_thrust_forces(throttles, HP, GP)
% calculate_thrust_forces - Calculates the total 3D force and moment vectors
%                           acting on the vehicle body from all active engines.
%
% Inputs:
%   throttles - Nx1 vector of throttle commands [0.0 to 1.0] for each engine
%   HP        - Hovercraft Parameters struct containing engine geometry
%   GP        - Global Parameters struct containing standard gravity
%
% Outputs:
%   Forces_body  - 3x1 vector of total forces [Fx; Fy; Fz] [N]
%   Moments_body - 3x1 vector of total moments [Mx; My; Mz] [Nm]
%   mdot_total   - Total instantaneous propellant mass flow rate [kg/s]

% Initialize accumulators
Forces_body  = zeros(3,1);
Moments_body = zeros(3,1);
mdot_total   = 0;

% Define the Center of Gravity offset vector
cg_vec = [0; 0; HP.mCG(3)];

for i = 1:HP.nEngines
    % Calculate the azimuthal angle of the current engine
    theta_rad = deg2rad((i-1) * HP.degEngineRadialAngle);

    % Define the 3D physical position of the engine
    pos_engine = [HP.mEngineRadialPos * cos(theta_rad);
        HP.mEngineRadialPos * sin(theta_rad);
        HP.mEngineAxialPos];

    % Calculate the moment arm vector (from C.G. to the engine nozzle)
    r_arm = pos_engine - cg_vec;

    % Convert commanded throttle percentage to mass flow rate (kg/s)
    mdot_i = throttles(i) * HP.gpsecMaxPropFlowRate / 1000;

    % Obtain the 3D thrust force vector generated by this specific engine
    T_vec = calculate_thrust_vec(HP.newtonMaxThrust, HP.secIsp, mdot_i, GP.g0, ...
        theta_rad, deg2rad(HP.degThrustRadialAngle));

    % Sum the forces and calculate moments using the cross product (M = r x F)
    Forces_body = Forces_body + T_vec;
    Moments_body = Moments_body + cross(r_arm, T_vec);
    mdot_total = mdot_total + mdot_i;
end

end